---
- hosts: localhost
  gather_facts: false
  vars_files:
    - vars.yml
  tasks:
    - name: Create EC2 key for deployment
      ec2_key:
        name: "{{ key_name }}"
        region: "{{ aws_region }}"
      register: key_result
    - name: Save private key to disk
      copy:
        content: "{{ key_result.key.private_key }}"
        dest: "~/.ssh/{{ key_name }}"
        mode: 0600
      when: key_result.changed 
    - name: Make EC2 machines
      ec2:
        key_name: "{{ key_name }}"
        instance_type: t2.micro
        image: "{{ ami_id }}"
        region: "{{ aws_region }}"
        wait: true
        exact_count: 1
        count_tag: 
          Name: "{{ item.name }}"
        instance_tags: 
          Name: "{{ item.name }}"
      register: ec2_result
      with_items: "{{ ec2_instances }}"
    - ec2_instance_info: 
      register: ec2_instance_info
    - copy: content="{{ ec2_instance_info }}" dest=./ec2.log
    - debug: var=ec2_instance_info
    - name: Build inventory from ec2 hosts
      add_host:
        name: "{{ item.public_dns_name }}"
        groups:  "name_{{ item.tags.Name }}"
        when: "{{ item.public_dns_name }}"
      with_items: "{{ ec2_instance_info.instances }}"
    - debug: var=groups 
    # - name: Make managed RDS
    #   rds:
    #     command: create
    #     db_engine: postgres
    #     db_name: todos
    #     username: "{{ rds_username }}"
    #     password: "{{ rds_password }}"
    #     instance_name: full-database
    #     instance_type: db.t3.micro
    #     size: 1GB
    #     region: "{{ aws_region }}"
    #   tags: rds



  # post_tasks:
  #   - name: refresh inventory
  #     meta: refresh_inventory
